# Generated by Django 2.2.1 on 2020-07-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cno', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=64)),
                ('faculty', models.CharField(max_length=64)),
                ('class_date', models.DateField(default=True)),
                ('class_time', models.CharField(max_length=54)),
                ('fees', models.FloatField(max_length=34)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
